server:
  port: 8080

knife4j:
  enable: true
  # 开启生产环境屏蔽
#  production: true
  documents:
    -
      group: alpha
      name: 测试自定义标题分组
      # 某一个文件夹下所有的.md文件
      locations: classpath:markdown/*
    -
      group: alpha      # 这个值和配置类中的匹配上后才显示
      name: 接口签名
      # 某一个文件夹下单个.md文件
      locations: classpath:markdown/api.md
    # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    # Basic认证用户名
    username: admin
    # Basic认证密码
    password: 123456
  setting:
    enableSwaggerModels: true
    swaggerModelName: 我是自定义的Model名称
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Apache License 2.0 | Copyright  2020-[陕西信产](https://gitee.com/xiaoym/knife4j)